language: ruby

before_install:
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.4.5
  - 2.5.4
  - 2.6.2
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
